export const allConversationHistory = [
  {
    avatar: null,
    partnerId: "2",
    partnerNm: "Tuong vy",
    status: "online",
    lastOnlineTm: null,
    lastMsg: {
      sender: false,
      msg: "Khau phat tam xa...",
      read: false,
    },
  },
  {
    avatar: null,
    partnerId: "3",
    partnerNm: "Hoai Nhu",
    status: "offline",
    lastOnlineTm: "20220627050500",
    lastMsg: {
      sender: false,
      msg: "Nha la phai co noc...",
      read: true,
    },
  },
  {
    avatar: null,
    partnerId: "4",
    partnerNm: "Thu Thao",
    status: "offline",
    lastOnlineTm: "20220627040400",
    lastMsg: {
      sender: false,
      msg: "Anh em dau, len ly!",
      read: true,
    },
  },
  {
    avatar: null,
    partnerId: "5",
    partnerNm: "Nana",
    status: "offline",
    lastOnlineTm: "20220627040400",
    lastMsg: {
      sender: true,
      msg: "Chi Huyen chu chi khong hien",
      read: false,
    },
  },
  {
    avatar: null,
    partnerId: "6",
    partnerNm: "Nhat Quy",
    status: "offline",
    lastOnlineTm: "20220627184400",
    lastMsg: {
      sender: false,
      msg: "I'm Ca khia xuyen luc dia",
      read: false,
    },
  },
  {
    avatar: null,
    partnerId: "1",
    partnerNm: "Thuy An",
    status: "online",
    lastOnlineTm: null,
    lastMsg: {
      sender: true,
      msg: "Khau xa tam phat...",
      read: true,
    },
  },
  {
    avatar: null,
    partnerId: "1",
    partnerNm: "Thuy An",
    status: "online",
    lastOnlineTm: null,
    lastMsg: {
      sender: true,
      msg: "Khau xa tam phat...",
      read: true,
    },
  },
  {
    avatar: null,
    partnerId: "1",
    partnerNm: "Thuy An",
    status: "online",
    lastOnlineTm: null,
    lastMsg: {
      sender: true,
      msg: "Khau xa tam phat...",
      read: true,
    },
  },
  {
    avatar: null,
    partnerId: "1",
    partnerNm: "Thuy An",
    status: "online",
    lastOnlineTm: null,
    lastMsg: {
      sender: true,
      msg: "Khau xa tam phat...",
      read: true,
    },
  },
  {
    avatar: null,
    partnerId: "1",
    partnerNm: "Thuy An",
    status: "online",
    lastOnlineTm: null,
    lastMsg: {
      sender: true,
      msg: "Khau xa tam phat...",
      read: true,
    },
  },
  {
    avatar: null,
    partnerId: "1",
    partnerNm: "Thuy An",
    status: "online",
    lastOnlineTm: null,
    lastMsg: {
      sender: true,
      msg: "Khau xa tam phat...",
      read: true,
    },
  },
  {
    avatar: null,
    partnerId: "1",
    partnerNm: "Thuy An",
    status: "online",
    lastOnlineTm: null,
    lastMsg: {
      sender: true,
      msg: "Khau xa tam phat...",
      read: true,
    },
  },
];