export const userList = [
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "normal",
    reportCount: 1,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "normal",
    reportCount: 1,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "normal",
    reportCount: 12,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "blocked",
    reportCount: 32,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "normal",
    reportCount: 312313,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "blocked",
    reportCount: 312,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "normal",
    reportCount: 45345,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "blocked",
    reportCount: 345,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "blocked",
    reportCount: 5665,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "blocked",
    reportCount: 0,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "blocked",
    reportCount: 0,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "blocked",
    reportCount: 0,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "blocked",
    reportCount: 0,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "blocked",
    reportCount: 0,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "blocked",
    reportCount: 0,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "blocked",
    reportCount: 0,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "blocked",
    reportCount: 0,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "blocked",
    reportCount: 0,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "blocked",
    reportCount: 0,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "blocked",
    reportCount: 0,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "blocked",
    reportCount: 32,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "blocked",
    reportCount: 32,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "blocked",
    reportCount: 234,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "blocked",
    reportCount: 243,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "normal",
    reportCount: 324,
  },
  {
    userId: "u1",
    userName: "VnsKing",
    email: "vnsking7899@gmail.com",
    status: "normal",
    reportCount: 234234,
  },
];